from __future__ import unicode_literals


class McMediainfo(object):
	page_url = ""
	title = ""
	eName = ""
	otherName = ""
	adaptor = ""
	director = ""
	leader = ""
	kind = ""
	language = ""
	duration = ""
	story = ""
	keyWord = ""
	productPerson = ""
	dubbing = ""
	executiver = ""
	original = ""
	productColtd = ""
	productionTime = ""
	licence = ""
	registration = ""
	distributColtd = ""
	totalNumber = ""
	updateInfo = ""
	area = ""
	source = ""
	playTime = ""
	producer = ""
	television = ""